Repository githubschool/big-crew, pull requests merged in 2019-09, with the labels that each got.

#19 Add new caption to picture
  _posts/0000-01-20-rwnfoo.md
Labels: good first issue, help wanted

#13 Changed the title
  _posts/0000-01-10-VBZelin.md
Labels: good first issue, help wanted

#23 Add new caption to my picture
  _posts/0000-01-14-CMPeng.md
Labels: good first issue, help wanted

#16 first edit, added caption
  _posts/0000-01-03-gpi63.md
Labels: help wanted

#18 Narayananl23 add caption
  _posts/0000-01-19-narayananl23.md
Labels: enhancement

#24 added new caption to picture
  _posts/0000-01-08-sumchat.md
Labels: help wanted

#20 Add caption to picture with my username
  _posts/0000-01-04-sean8054.md
Labels: documentation

#15 Add new caption to picture
  _posts/0000-01-05-chall13.md
Labels: good first issue

#12 Add new caption to picture.
  _posts/0000-01-06-driggins-work.md
Labels: help wanted, question

#22 Add new caption to pic
  _posts/0000-01-16-mgullon.md
Labels: help wanted
